// Code generated by go generate; DO NOT EDIT.

package ima_standalone_v0_0_1

const SigningHash = "39a9596ddd01cf6da050484e37e7e62eb5c09acfd549d4e8988b604443f7fa607d8970abae640cca10bcba04617c2b88bfcd373d17f06e0782c5e2dacb7f1dfe"
