// Code generated by go generate; DO NOT EDIT.

package trustmodel_ima_mec_v0_0_1

const SigningHash = "e17763e427439baccdffed63ce04456b4e684c2fb540e033aa62526e4aa36d39ff89e89967ce5702694002bb9e80e22342df23b5b4c9cadd7d28ea9bf7dcb426"
