// Code generated by go generate; DO NOT EDIT.

package trustmodel_vcm_v0_0_1

const SigningHash = "d8e85aed0b7560a8e1a4e626bf1bf633e264e70ab47a939fddf58684942be2db65660824266d0e5f934b3bc3c8e5dc4135577f59768cebbdc61993f1b5335bfd"
