// Code generated by go generate; DO NOT EDIT.

package trustmodel_vcm_v0_0_1

const SigningHash = "c39b690319e9fa93a8cc544bbf95fbe64e9f5396270bd24195c7075097e169b80e85102956f2ab3dcb419e747d36abab83c4c1569851c8b05af3e663bde3310b"
