image: golang:latest

stages:
  - test
  - build
  - pages

test:
  stage: test
  script:
    - make check
    - make bench

build:
  stage: build
  script:
    - make build
  artifacts:
    paths:
      - out
      - plugins/bin

.pages:
  stage: pages
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go/bin
    - mkdir -p .go/src
    - mkdir -p .go/pkg
  cache:
    paths:
      - .go/
  environment:
    name: pages
    url: https://connect.p.lxd-vs.uni-ulm.de/taf-scalability-test
  artifacts:
    paths:
      - public/
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - go install golang.org/x/pkgsite/cmd/pkgsite@latest
    - export PATH=${PATH}:`go env GOPATH`/bin
    - make docs
    - mv docs/ public/
    - echo '/taf-scalability-test/ /taf-scalability-test/gitlab-vs.informatik.uni-ulm.de/connect/taf-brussels-demo/ 302' > public/_redirects

