stages:
  - test
  - release

variables:
  GITLAB_DEPENDENCIES: "coordination/tlee-implementation coordination/crypto-library-interface"

default:
  image: golang:1.22
  cache:
    paths:
      - .cache
      - .dependencies
  before_script:
    - mkdir -p .cache
    - mkdir -p .dependencies
    - export GOPATH="$CI_PROJECT_DIR/.cache"
    - |      
      for DEP in $GITLAB_DEPENDENCIES; do
        git version || continue
        d="$(echo $DEP | sed 's/.*\///')"
        ln -sf $CI_PROJECT_DIR/.dependencies/$d ../$d
        git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@connect.informatik.uni-ulm.de/${DEP} .dependencies/$d && continue
        cd .dependencies/$d
        sed -i "s/\(\/\/gitlab-ci-token:\)[^@]*/\1${CI_JOB_TOKEN}/" .git/config
        git reset --hard
        git clean -df
        git pull
        cd $CI_PROJECT_DIR
      done

check:
  stage: test
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always
  script:
    - make

build:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |      
      make ${MAKE_TARGET}
      filename="$(basename out/main* | sed "s/main/go-taf$(echo $MAKE_TARGET | sed 's/build//')/")"
      curl --fail-with-body -H "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file out/main* "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${GOOS}-${GOARCH}/${CI_COMMIT_TAG}/${filename}${suffix}"
  parallel:
    matrix:
      - GOOS: windows
        GOARCH: [386, amd64]
        MAKE_TARGET: [build, build-with-webui]
      - GOOS: linux
        GOARCH: [386, amd64]
        MAKE_TARGET: [build, build-with-webui]
      - GOOS: darwin
        GOARCH: [amd64, arm64]
        MAKE_TARGET: [build, build-with-webui]
changelog:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - mkdir -p out
    - sed -n '/^\x23\x23 /{h; n; :a; /^\x23\x23 /!{H; n; ba}; x; p; q}' Changelog.md > out/Description.md
  artifacts:
    paths:
      - out/
    expire_in: 1d

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: build
    - job: changelog
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "create release"
  release:
    tag_name: '$CI_COMMIT_TAG'
    description: './out/Description.md'
    assets:
      links:
        - link_type: 'package'
          name: "go-taf_windows-amd64.exe"
          url: '${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/windows-amd64/${CI_COMMIT_TAG}/go-taf.exe'
        - link_type: 'package'
          name: 'go-taf_windows-386.exe'
          url: '${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/windows-386/${CI_COMMIT_TAG}/go-taf.exe'
        - link_type: 'package'
          name: 'go-taf_linux-amd64'
          url: '${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/linux-amd64/${CI_COMMIT_TAG}/go-taf'
        - link_type: 'package'
          name: 'go-taf_linux-386'
          url: '${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/linux-386/${CI_COMMIT_TAG}/go-taf'
        - link_type: 'package'
          name: 'go-taf_darwin-arm64'
          url: '${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/darwin-arm64/${CI_COMMIT_TAG}/go-taf'
        - name: 'go-taf_darwin-amd64'
          link_type: 'package'
          url: '${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/darwin-amd64/${CI_COMMIT_TAG}/go-taf'
        - link_type: 'package'
          name: "go-taf-with-webui_windows-amd64.exe"
          url: '${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/windows-amd64/${CI_COMMIT_TAG}/go-taf-with-webui.exe'
        - link_type: 'package'
          name: 'go-taf-with-webui_windows-386.exe'
          url: '${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/windows-386/${CI_COMMIT_TAG}/go-taf-with-webui.exe'
        - link_type: 'package'
          name: 'go-taf-with-webui_linux-amd64'
          url: '${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/linux-amd64/${CI_COMMIT_TAG}/go-taf-with-webui'
        - link_type: 'package'
          name: 'go-taf-with-webui_linux-386'
          url: '${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/linux-386/${CI_COMMIT_TAG}/go-taf-with-webui'
        - link_type: 'package'
          name: 'go-taf-with-webui_darwin-arm64'
          url: '${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/darwin-arm64/${CI_COMMIT_TAG}/go-taf-with-webui'
        - name: 'go-taf-with-webui_darwin-amd64'
          link_type: 'package'
          url: '${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/darwin-amd64/${CI_COMMIT_TAG}/go-taf-with-webui'
