// Code generated by go generate; DO NOT EDIT.
// This file was generated automatically at
// 2024-11-22 17:01:52.110313075 +0100 CET m=+0.000842432
package brussels_0_0_1

const SigningHash = "4fb4077fd1a8c07692093bd4408fa2f4fd33ceeeb833afbb7d3bd3c0841bdbd01b2648e47405d5338e54d46a27abba66aad3e4176a3812da2c3650445aebaa9b"
