// Code generated by go generate; DO NOT EDIT.

package brussels_0_0_1

const SigningHash = "2b1cb28b2bcf5ab52716163a20997ca8ff52fed44d414f0184d5586fdc89d96f387dbd233d40b0a90a291a8eb1c58ecfcdfa5727801d2a57071833a3d957b4d9"
