// Code generated by go generate; DO NOT EDIT.

package trustmodel_smtd_v0_0_1

const SigningHash = "89db1f045688cbcba0d53e593baf9b194a1f1f164dbdb01247b73001b594f99520a7d08bc9ae139bb7178cc7e3667c44628b8c527af56b3688d1642553d5b898"
