// Code generated by go generate; DO NOT EDIT.

package trustmodel_smtd_v0_0_1

const SigningHash = "9be944f34d7debc74b6040ea41f0d758a2918525700a14c88513df08e3b764cacbf3206b1ba7887225e086a9c5b645f3dac133032fdf25a658b109478247e63a"
