// Code generated by go generate; DO NOT EDIT.

package example_v0_0_1

const SigningHash = "505b3960551e3c5f61be3b206ff96b16106f40b300c876d7464912985d86cfc3a7c2046b8fb52c28f482a833505646081acaa4737c5c2f082f6bb27e39d6caee"
