// Code generated by go generate; DO NOT EDIT.

package smtd_v0_0_1

const SigningHash = "5fa3434a7a6d865c3d9bc658217935123276278a3c12809b2f1a6b04f20041966bf28ad73c70db1d1727f9efb7ff74e76de394262007ed89caa439d843e4ca3b"
