// main generates cmd/plugin_loader.go.
// plugin_loader.go consists of import statements for each plugin found under plugins/
// This is necessary because we want 1) out plugins under plugins/ 2) no explicit knowledge
// which plugins exist in non-generated files in pkg/ or cmd/.
package main

import (
	"bufio"
	"fmt"
	"io/fs"
	"log"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"text/template"
	"time"
)

// Read and return the module name from go.mod
func getModuleName() string {
	f, err := os.Open(filepath.FromSlash("../go.mod"))
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := scanner.Text()
		if modname, ok := strings.CutPrefix(line, "module "); ok {
			return modname
		}
	}

	if err = scanner.Err(); err != nil {
		log.Fatal(err)
	}
	log.Fatal("module name not found in go.mod")
	return ""
}

func main() {
	pluginList := []string{}
	fileSystem := os.DirFS("..")
	BaseURL := getModuleName()

	// get a  listing of all go files in the plugins directory and store the paths to the directories (=packages)
	// they are in.
	err := fs.WalkDir(fileSystem, filepath.FromSlash("plugins"), func(path string, d fs.DirEntry, err error) error {
		if strings.HasSuffix(path, ".go") && !strings.HasSuffix(path, "plugins.go") {
			packageName := "/" + filepath.Dir(path)
			packageName = strings.ReplaceAll(packageName, "\\", "/")
			pluginList = append(pluginList, packageName)
		}
		return nil
	})
	if err != nil {
		log.Fatal(err)
	}

	// Sort the list of packages and remove duplicates
	slices.Sort(pluginList)
	pluginList = slices.Compact(pluginList)

	log.Printf("discovered the following plugins: %+v\n", pluginList)

	pluginImportList := []string{}
	for _, plugin := range pluginList {
		importStr := fmt.Sprintf("import _ \"%s%s\"", BaseURL, plugin)
		pluginImportList = append(pluginImportList, importStr)
	}

	f, err := os.Create("plugin_loader.go")
	if err != nil {
		log.Fatalln(err)
	}
	defer f.Close()

	packageTemplate.Execute(f, struct {
		Timestamp time.Time
		Imports   []string
	}{
		Timestamp: time.Now(),
		Imports:   pluginImportList,
	})

}

var packageTemplate = template.Must(template.New("").Parse(`// Code generated by go generate; DO NOT EDIT.
// This file was generated automatically at
// {{ .Timestamp }}
package main

{{- range .Imports }}
{{ printf . }}
{{- end }}
`))
