// Code generated by go generate; DO NOT EDIT.

package trustmodel_to_v0_0_1

const SigningHash = "f899d9d03de859158e7bd6d7f01adf3d40f34f049d5ff9dda4e54a8ae6540eff7d5655cb99f9fe5c4bb7c927cfac8324383e68efe834af0b4e2b24784a01bcb9"
