// Code generated by go generate; DO NOT EDIT.

package trustmodel_to_v0_0_1

const SigningHash = "1ffb3fc769605e9c45a251117e0470b1fdb2672fa70138d02cafef786a5a3cd9e9b8cbfadbb29f543f712fe5f39b7dd671be52f36ac4b01476e9d64c5689f518"
