// Code generated by go generate; DO NOT EDIT.

package to_v0_0_1

const SigningHash = "f0d98400979e8f25d2a46c0dd873f0c03f650aa7aac93187dfd045656aaaf01e1042fdd23078711b0a5f9f6d53de93da083b54f3faabb29c5115a5d8c02c37d5"
