// Code generated by go generate; DO NOT EDIT.
// This file was generated automatically at
// 2024-06-28 20:05:17.131611446 +0200 CEST m=+0.005398034
package main

import _ "github.com/vs-uulm/go-taf/plugins/evidencecollection/attestation"
import _ "github.com/vs-uulm/go-taf/plugins/tam/add"
import _ "github.com/vs-uulm/go-taf/plugins/tam/mult"
