// Code generated by go generate; DO NOT EDIT.
// This file was generated automatically at
// 2024-03-25 15:52:24.083108852 +0100 CET m=+0.000479797
package main

import _ "gitlab-vs.informatik.uni-ulm.de/connect/taf-brussels-demo/plugins/evidencecollection/attestation"
import _ "gitlab-vs.informatik.uni-ulm.de/connect/taf-brussels-demo/plugins/tam/add"
import _ "gitlab-vs.informatik.uni-ulm.de/connect/taf-brussels-demo/plugins/tam/mult"
