// Code generated by go generate; DO NOT EDIT.
// This file was generated automatically at
// 2024-03-28 16:49:54.234735105 +0100 CET m=+0.360166191
package main

import _ "github.com/vs-uulm/go-taf/plugins/evidencecollection/attestation"
import _ "github.com/vs-uulm/go-taf/plugins/tam/add"
import _ "github.com/vs-uulm/go-taf/plugins/tam/mult"
