// Code generated by go generate; DO NOT EDIT.
// This file was generated automatically at
// 2024-11-22 17:01:52.111227661 +0100 CET m=+0.001757018
package ima_mec_v0_0_1

const SigningHash = "dfb49d0f6db0e8b41e752c1bba594cce031fd46fa1bd8065b8f74ca41abaca1ebf0540be19802bfa12592310bc9e4abdfb7b3522bb199a85f1d623ee1c84b249"
