package core

/*
A CommandType indicates the type of internal command to be by the TAM/TSM/TMM.
*/
type CommandType uint16

const (
	UNDEFINED CommandType = iota
	HANDLE_TAQI_QUERY
	HANDLE_TAQI_RESULT
	HANDLE_TAS_INIT_REQUEST
	HANDLE_TAS_TEARDOWN_REQUEST
	HANDLE_TAS_TA_REQUEST
	HANDLE_TAS_SUBSCRIBE_REQUEST
	HANDLE_TAS_UNSUBSCRIBE_REQUEST
	HANDLE_AIV_RESPONSE
	HANDLE_AIV_SUBSCRIBE_RESPONSE
	HANDLE_AIV_UNSUBSCRIBE_RESPONSE
	HANDLE_AIV_NOTIFY
	HANDLE_MBD_SUBSCRIBE_RESPONSE
	HANDLE_MBD_NOTIFY
	HANDLE_MBD_UNSUBSCRIBE_RESPONSE
	HANDLE_TCH_NOTIFY
	HANDLE_V2X_CPM
	HANDLE_V2X_NTM
	HANDLE_TMI_INIT
	HANDLE_TMI_UPDATE
	HANDLE_TMI_DESTROY
	HANDLE_ATL_UPDATE
)

func (c CommandType) String() string {
	return [...]string{"UNDEFINED",
		"HANDLE_TAS_INIT_REQUEST",
		"HANDLE_TAS_TEARDOWN_REQUEST",
		"HANDLE_TAS_TA_REQUEST",
		"HANDLE_TAS_SUBSCRIBE_REQUEST",
		"HANDLE_TAS_UNSUBSCRIBE_REQUEST",
		"HANDLE_AIV_RESPONSE",
		"HANDLE_AIV_SUBSCRIBE_RESPONSE",
		"HANDLE_AIV_UNSUBSCRIBE_RESPONSE",
		"HANDLE_AIV_NOTIFY",
		"HANDLE_MBD_SUBSCRIBE_RESPONSE",
		"HANDLE_MBD_NOTIFY",
		"HANDLE_MBD_UNSUBSCRIBE_RESPONSE",
		"HANDLE_TCH_NOTIFY",
		"HANDLE_V2X_CPM",
		"HANDLE_V2X_NTM",
		"HANDLE_TMI_INIT",
		"HANDLE_TMI_UPDATE",
		"HANDLE_TMI_DESTROY",
		"HANDLE_ATL_UPDATE",
	}[c]
}

type Command interface {
	Type() CommandType
}
