package core

type CommandType int64

const (
	UNDEFINED CommandType = iota
	HANDLE_TAS_INIT_REQUEST
	HANDLE_TAS_TEARDOWN_REQUEST
	HANDLE_TAS_TA_REQUEST
	HANDLE_TAS_SUBSCRIBE_REQUEST
	HANDLE_TAS_UNSUBSCRIBE_REQUEST
	HANDLE_AIV_RESPONSE
	HANDLE_AIV_SUBSCRIBE_RESPONSE
	HANDLE_AIV_UNSUBSCRIBE_RESPONSE
	HANDLE_AIV_NOTIFY
	HANDLE_MBD_SUBSCRIBE_RESPONSE
	HANDLE_MBD_NOTIFY
	HANDLE_MBD_UNSUBSCRIBE_RESPONSE
	HANDLE_TCH_NOTIFY
)

type Command interface {
	Type() CommandType
}
