// Code generated by go generate; DO NOT EDIT.

package trustmodel_example_v0_0_1

const SigningHash = "912f80161e9e45a138d6042b03e865ecb4c45a6d4c57d99b66563342d83f90194dbff84542b8b5ab769253d672baaa5f3a86238bf70f5598d4e80b44f082f6c8"
