name: Release Binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24' # update as needed

    - name: Build binaries
      run: |
        mkdir -p dist
        GOOS=linux GOARCH=amd64 go build -tags webui ./cmd/main.go ./cmd/plugin_loader.go -o dist/go-taf-linux-amd64
        GOOS=darwin GOARCH=amd64 go build -tags webui ./cmd/main.go ./cmd/plugin_loader.go -o dist/go-taf-darwin-amd64
        GOOS=windows GOARCH=amd64 go build -tags webui ./cmd/main.go ./cmd/plugin_loader.go -o dist/go-taf-windows-amd64.exe

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: dist/*

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
