// Code generated by go generate; DO NOT EDIT.
// This file was generated automatically at
// 2024-11-22 17:01:52.112192891 +0100 CET m=+0.002722248
package vcm_v0_0_1

const SigningHash = "929e20bdcf2a5f9769b11a34d0209690bdbebd5d6142dda70153c841753b74ef1890b9c993e2c51f5720ff5018149bcc60ce2f366ec40a2c0a1e65e8193d03a8"
